name = "zachhandley"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-15"
pages_build_output_dir = "dist"

# Not using Astro Sessions rn
# kv_namespaces = [
#     { binding = "SESSION", id = "" },
# ]

[vars]
NODE_VERSION = "22.11.0"