<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./public/models/Mountain_Group_2.gltf --types --shadows --transform
-->

<script lang="ts">
  import type * as THREE from "three";

  import type { Snippet } from "svelte";
  import { T, type Props } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
  import type { DRACOLoader } from "three/examples/jsm/Addons.js";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    dracoLoader,
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
    dracoLoader: DRACOLoader;
  } = $props();

  type GLTFResult = {
    nodes: {
      Cube044: THREE.Mesh;
      Cube044_1: THREE.Mesh;
      Cube044_2: THREE.Mesh;
    };
    materials: {
      Stone: THREE.MeshStandardMaterial;
      Snow: THREE.MeshStandardMaterial;
      Dirt: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>("/models/Mountain_Group_2-transformed.glb", {
    dracoLoader,
  });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube044.geometry}
      material={gltf.materials.Stone}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube044_1.geometry}
      material={gltf.materials.Snow}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube044_2.geometry}
      material={gltf.materials.Dirt}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
