<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./public/models/Temple_SecondAge_Level3.gltf --types --shadows --transform
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import type { DRACOLoader } from 'three/examples/jsm/Addons.js'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    dracoLoader,
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    dracoLoader: DRACOLoader
  } = $props()

  type GLTFResult = {
    nodes: {
      Cube223: THREE.Mesh
      Cube223_1: THREE.Mesh
      Cube223_2: THREE.Mesh
    }
    materials: {
      Walls: THREE.MeshStandardMaterial
      Main: THREE.MeshStandardMaterial
      Stone: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Temple_SecondAge_Level3-transformed.glb', {
    dracoLoader,
  })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube223.geometry}
      material={gltf.materials.Walls}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube223_1.geometry}
      material={gltf.materials.Main}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube223_2.geometry}
      material={gltf.materials.Stone}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
