name = "zachhandley"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
workers_dev = false
'$schema' = "node_modules/wrangler/config-schema.json"
main = "dist/_worker.js/index.js"
[assets]
binding = "ASSETS"
directory = "./dist"

# Not using Astro Sessions rn
# kv_namespaces = [
#     { binding = "SESSION", id = "" },
# ]