name = "zachhandley"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-15"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "ZSESSION"
id = "df4e65f081824d0cb86b29afb2a83f60"

[vars]
NODE_VERSION = "22.11.0"