name = "astro-worker"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
workers_dev = false
assets.directory = "./dist"
'$schema' = "node_modules/wrangler/config-schema.json"

# Not using Astro Sessions rn
# kv_namespaces = [
#     { binding = "SESSION", id = "" },
# ]