# Workflow for deploying ZachHandley.com
name: Dev Deployment (For CF Preview)

on:
  push:
    branches:
      - dev
  # Runs on release publish
  release:
    types: [published]
  # Allows manual trigger
  workflow_dispatch:

# Set permissions
permissions:
  actions: write
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "dev-frontend-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to own branch for CF Builder
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: website
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: {sha} - {msg}"
