# Workflow for deploying ZachHandley.com
name: Frontend Deployment

on:
  push:
    branches:
      - main
  # Runs on release publish
  release:
    types: [published]
  # Allows manual trigger
  workflow_dispatch:

# Set permissions
permissions:
  actions: write
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "frontend-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: website

      - name: Build website
        run: pnpm build
        working-directory: website

      - name: Deploy to own branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: website/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: {sha} - {msg}"
